# Generated by Django 4.2.26 on 2025-11-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationsummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='conversationsummary',
            new_name='slackbot_co_target__c25c46_idx',
            old_name='slackbot_c_target__3a780b_idx',
        ),
    ]
