# Generated by Django 4.2.26 on 2025-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='doc_manager_status_dfc56a_idx'), models.Index(fields=['created_at'], name='doc_manager_created_be8b39_idx')],
            },
        ),
    ]
